name: contentful_sdk
description: Contentful SDK designed to provide support for Contentful Delivery, Preview & Management APIs.
version: 0.1.0
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.2
  json_annotation: ^4.0.1
  equatable: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.1
  json_serializable: ^4.1.1


